#cloud-config
users:
  - name: containers
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxpsYqWt4xha0TSLdCyxe4B4i7twdboLEsZgzsaRdqzDiSdRyQf58b9OL2mtfsHf3BnQjBvnlOc9oFxifDvdCHT8y9Z7z6e4U5bRhq+DaympF91j7xvGS6jmI5Nd8SFyfb4tas/xd/mLDF0rb+7/IzKD1p9kmSdtd6BeoVgz3p5KLCg3jiSam8lFb6IzjHaTBoYvUZOm8mLMKn51d8WZiXymQMUlX0GUktOcMe66Sy82QmxIesjUJnAGvtvDMsLbhwAkFWP+gefZM08MPh3ANA7DUzM4lwnK8XQsOIj+uVadC4nRM383Tb44Ft9richOQMm+Ze7O6/Oi96LWyJR9sOervTmDi4E7jsuNIMtXT2n7/WWarCrheCFraLgOl1gqUXNhm+iB2nNxQWYiKobanoNej4dmT/Om+jazqR/9yqkWPYmEZqb5o7L+PhivCB//zWb3LT5LAQt0xQKjSVoUldNLvmMT7vv9ZbtqQ+qBxPIxevUMvmXPoeF6OGTeufnJh80O3wg2H4j1LJ8/tLCHjw8jhzF0qQsWoGMuOG6nVnIRIWdr9gvaP0VO0ebXyYgVy85ZgIukXEKZpjOJjbscSpQtzldQo5kLv4WOgdEVufEAddBo5wyouO5CDvNxOsvUoQg3EtgMPDdutabfnt3MB2IFEXD9Hmx4cEWRgz43vDdw== leaddev@fedora
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - fail2ban
  - ufw
runcmd:
  # Configure firewall and fail2ban
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw allow 'OpenSSH'
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw enable
  # Configure SSH
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers containers' /etc/ssh/sshd_config
  - systemctl restart ssh
  # Install docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker containers
  - systemctl enable docker
      
